/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'house' : IDL.Null,
  'other' : IDL.Null,
  'land' : IDL.Null,
  'apartment' : IDL.Null,
});
export const UsageType = IDL.Variant({
  'investment' : IDL.Null,
  'selfUse' : IDL.Null,
});
export const LeadCaptureFormData = IDL.Record({
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'usageType' : UsageType,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'formData' : LeadCaptureFormData,
  'submittedBy' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func([LeadCaptureFormData], [IDL.Nat], []),
  'updateLead' : IDL.Func([IDL.Nat, LeadCaptureFormData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'house' : IDL.Null,
    'other' : IDL.Null,
    'land' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const UsageType = IDL.Variant({
    'investment' : IDL.Null,
    'selfUse' : IDL.Null,
  });
  const LeadCaptureFormData = IDL.Record({
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'usageType' : UsageType,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
  });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'formData' : LeadCaptureFormData,
    'submittedBy' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func([LeadCaptureFormData], [IDL.Nat], []),
    'updateLead' : IDL.Func([IDL.Nat, LeadCaptureFormData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };