/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'formData' : LeadCaptureFormData,
  'submittedBy' : Principal,
  'timestamp' : Time,
}
export interface LeadCaptureFormData {
  'propertyType' : PropertyType,
  'name' : string,
  'usageType' : UsageType,
  'phone' : string,
  'budget' : string,
}
export type PropertyType = { 'commercial' : null } |
  { 'house' : null } |
  { 'other' : null } |
  { 'land' : null } |
  { 'apartment' : null };
export type Time = bigint;
export type UsageType = { 'investment' : null } |
  { 'selfUse' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[bigint], Lead>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[LeadCaptureFormData], bigint>,
  'updateLead' : ActorMethod<[bigint, LeadCaptureFormData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];